pub mod lexer;
pub mod parser;
pub mod tokens;

use serde::{Deserialize, Serialize};
use std::fs;

use lexer::Lexer;
use parser::Parser;

// Defines parsing actions generated by the LALR parser table
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
#[serde(tag = "type", content = "value")]
pub enum Action {
    #[serde(rename = "SHIFT")]
    Shift(usize),
    #[serde(rename = "REDUCE")]
    Reduce(usize),
    #[serde(rename = "ERROR")]
    Error(i32),
    #[serde(rename = "ACCEPT")]
    Accept(usize),
}

// Represents the complete structure of the generated parsing table
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Table {
    pub num_states: usize,
    pub num_terminals_with_eof: usize,
    pub num_non_terminals: usize,
    pub has_conflicts: bool,
    pub num_conflicts: usize,
    pub terminals: Vec<String>,
    pub non_terminals: Vec<String>,
    pub action: Vec<Vec<Action>>,
    pub goto: Vec<Vec<i32>>,
    pub productions: Vec<parser::Production>,
}

fn main() {
    // Parse command line arguments for the source file and parse table
    let args: Vec<String> = std::env::args().collect();
    if args.len() != 3 {
        eprintln!("Usage: {} <source_file> <parse_table>", args[0]);
        std::process::exit(1);
    }

    let source_file = &args[1];
    let parse_table_file = &args[2];

    // Load and deserialize the parse table
    let table_content = fs::read_to_string(parse_table_file)
        .unwrap_or_else(|_| panic!("Failed to read parse table: {}", parse_table_file));

    let table: Table = serde_json::from_str(&table_content).expect("Failed to parse table JSON");

    // Load the input source code
    let source_content = fs::read_to_string(source_file)
        .unwrap_or_else(|_| panic!("Failed to read source file: {}", source_file));

    println!("Successfully loaded source file: {}", source_file);
    println!(
        "Successfully loaded parse table with {} states",
        table.num_states
    );

    // Initialize the lexer and parser using the provided table and source content
    let lexer = Lexer::new(&source_content);
    let productions = table.productions.clone();
    let parser = Parser::new(table, productions);

    // Perform syntax analysis on the token stream
    match parser.parse(lexer) {
        Ok(ast) => {
            println!("Parsing successful!");
            println!("AST: {:#?}", ast);
        }
        Err(e) => {
            eprintln!("\nParse error: {}", e);
            std::process::exit(1);
        }
    }
}
