// Represents the possible token types that the lexer can produce
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u32)]
pub enum ScannerToken {
    Eof = 0,
    Error = 256,

    KwInt,
    KwFloat,
    KwDouble,
    KwChar,
    KwVoid,
    KwIf,
    KwElse,
    KwWhile,
    KwFor,
    KwReturn,
    KwBreak,
    KwContinue,

    Identifier,
    IntLiteral,
    FloatLiteral,
    StringLiteral,
    CharLiteral,

    Inc,
    Dec,
    PlusAssign,
    MinusAssign,
    MulAssign,
    DivAssign,
    ModAssign,
    Assign,

    Eq,
    Neq,
    Lt,
    Le,
    Gt,
    Ge,

    And,
    Or,
    Not,

    Plus,
    Minus,
    Mul,
    Div,
    Mod,

    Lparen,
    Rparen,
    Lbrace,
    Rbrace,
    Lbracket,
    Rbracket,
    Comma,
    Semicolon,
    Colon,
}

impl ScannerToken {
    // Converts the token kind into a string representation that matches the grammar symbols
    pub fn get_symbol(&self) -> String {
        let t = match self {
            ScannerToken::Eof => "$",
            ScannerToken::Error => "err",
            ScannerToken::KwInt => "int",
            ScannerToken::KwFloat => "float",
            ScannerToken::KwDouble => "double",
            ScannerToken::KwChar => "char",
            ScannerToken::KwVoid => "void",
            ScannerToken::KwIf => "if",
            ScannerToken::KwElse => "else",
            ScannerToken::KwWhile => "while",
            ScannerToken::KwFor => "for",
            ScannerToken::KwReturn => "return",
            ScannerToken::KwBreak => "break",
            ScannerToken::KwContinue => "continue",
            ScannerToken::Identifier => "id",
            ScannerToken::IntLiteral => "num",
            ScannerToken::FloatLiteral => "num",
            ScannerToken::StringLiteral => "str",
            ScannerToken::CharLiteral => "char_lit",
            ScannerToken::Inc => "inc",
            ScannerToken::Dec => "dec",
            ScannerToken::PlusAssign => "+=",
            ScannerToken::MinusAssign => "-=",
            ScannerToken::MulAssign => "*=",
            ScannerToken::DivAssign => "/=",
            ScannerToken::ModAssign => "%=",
            ScannerToken::Assign => "=",
            ScannerToken::Eq => "==",
            ScannerToken::Neq => "!=",
            ScannerToken::Lt => "<",
            ScannerToken::Le => "<=",
            ScannerToken::Gt => ">",
            ScannerToken::Ge => "=>",
            ScannerToken::And => "&&",
            ScannerToken::Or => "||",
            ScannerToken::Not => "!",
            ScannerToken::Plus => "+",
            ScannerToken::Minus => "-",
            ScannerToken::Mul => "*",
            ScannerToken::Div => "/",
            ScannerToken::Mod => "%",
            ScannerToken::Lparen => "(",
            ScannerToken::Rparen => ")",
            ScannerToken::Lbrace => "{",
            ScannerToken::Rbrace => "}",
            ScannerToken::Lbracket => "[",
            ScannerToken::Rbracket => "]",
            ScannerToken::Comma => ",",
            ScannerToken::Semicolon => ";",
            ScannerToken::Colon => ":",
        };

        t.into()
    }
}
